"""initial schema

Revision ID: c3c53f442668
Revises: 
Create Date: 2026-07-22 04:04:29.686182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c53f442668'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'RESEARCHER', 'OPERATOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('clusters',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'WARNING', 'CRITICAL', 'OFFLINE', name='clusterstatus'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_id'), 'clusters', ['id'], unique=False)
    op.create_index(op.f('ix_clusters_name'), 'clusters', ['name'], unique=True)
    op.create_index(op.f('ix_clusters_owner_id'), 'clusters', ['owner_id'], unique=False)
    op.create_table('experiments',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('dataset_name', sa.String(length=200), nullable=True),
    sa.Column('allocated_gpus', sa.Integer(), nullable=False),
    sa.Column('allocated_cpus', sa.Integer(), nullable=False),
    sa.Column('allocated_memory_gb', sa.Float(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'STOPPED', name='experimentstatus'), nullable=False),
    sa.Column('guardian_score', sa.Float(), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_cluster_id'), 'experiments', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_experiments_id'), 'experiments', ['id'], unique=False)
    op.create_index(op.f('ix_experiments_user_id'), 'experiments', ['user_id'], unique=False)
    op.create_table('nodes',
    sa.Column('hostname', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('cpu_model', sa.String(length=150), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('gpu_model', sa.String(length=150), nullable=True),
    sa.Column('gpu_count', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.Float(), nullable=False),
    sa.Column('storage_gb', sa.Float(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('gpu_usage', sa.Float(), nullable=False),
    sa.Column('memory_usage', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('power_consumption', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'MAINTENANCE', 'FAILED', name='nodestatus'), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_index(op.f('ix_nodes_cluster_id'), 'nodes', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_nodes_hostname'), 'nodes', ['hostname'], unique=True)
    op.create_index(op.f('ix_nodes_id'), 'nodes', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prediction_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='predictionstatus'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('predicted_label', sa.String(length=100), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_cluster_id'), 'predictions', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_node_id'), 'predictions', ['node_id'], unique=False)
    op.create_index(op.f('ix_predictions_predicted_at'), 'predictions', ['predicted_at'], unique=False)
    op.create_table('telemetry',
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('cpu_temperature', sa.Float(), nullable=False),
    sa.Column('cpu_frequency', sa.Float(), nullable=False),
    sa.Column('gpu_usage', sa.Float(), nullable=False),
    sa.Column('gpu_temperature', sa.Float(), nullable=False),
    sa.Column('gpu_memory_usage', sa.Float(), nullable=False),
    sa.Column('gpu_power', sa.Float(), nullable=False),
    sa.Column('ram_usage', sa.Float(), nullable=False),
    sa.Column('swap_usage', sa.Float(), nullable=False),
    sa.Column('disk_usage', sa.Float(), nullable=False),
    sa.Column('disk_read_speed', sa.Float(), nullable=False),
    sa.Column('disk_write_speed', sa.Float(), nullable=False),
    sa.Column('network_in', sa.Float(), nullable=False),
    sa.Column('network_out', sa.Float(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('packet_loss', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_cluster_id'), 'telemetry', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_telemetry_id'), 'telemetry', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_node_id'), 'telemetry', ['node_id'], unique=False)
    op.create_index(op.f('ix_telemetry_recorded_at'), 'telemetry', ['recorded_at'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('threat_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='threatlevel'), nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'READ', name='notificationstatus'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_cluster_id'), 'notifications', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_node_id'), 'notifications', ['node_id'], unique=False)
    op.create_index(op.f('ix_notifications_prediction_id'), 'notifications', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_prediction_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_node_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_cluster_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_telemetry_recorded_at'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_node_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_cluster_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_predictions_predicted_at'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_node_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_cluster_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_nodes_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_hostname'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_cluster_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_experiments_user_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_cluster_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_clusters_owner_id'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_name'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_id'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
